services:
  auth-service:
    container_name: auth-service
    build:
      context: ./apps
      dockerfile: auth-service/Dockerfile
    env_file:
      - .env
    expose:
      - "3000"
    volumes:
      - ./apps/auth-service/data:/apps/auth-service/data
    networks:
      - transcendence
  user-service:
    container_name: user-service
    build:
      context: ./apps
      dockerfile: user-service/Dockerfile
    env_file:
      - .env
    expose:
      - "3001"
    volumes:
      - ./apps/user-service/data:/apps/user-service/data
    networks:
      - transcendence
  notification-service:
    container_name: notification-service
    build:
      context: ./apps
      dockerfile: notification-service/Dockerfile
    env_file:
      - .env
    expose:
      - "3002"
    volumes:
      - ./apps/notification-service/data:/apps/notification-service/data
    networks:
      - transcendence
  frontend:
    container_name: frontend
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./apps/frontend/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./apps/frontend/src/index.html:/usr/share/nginx/html/index.html:ro
    networks:
      - transcendence
    depends_on:
      - auth-service
      # - user-service
      - notification-service
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - transcendence
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - "7900:3000"
    env_file:
      - .env
    volumes:
      - ./monitoring/grafana/data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
    networks:
      - transcendence

networks:
  transcendence:
    driver: bridge
