services:
  auth-service:
    container_name: auth_service
    build:
      context: ./apps
      dockerfile: auth-service/Dockerfile
    env_file:
      - .env
    networks:
      - transcendence
  user-service:
    container_name: user-service
    build:
      context: ./apps
      dockerfile: user-service/Dockerfile
    env_file:
      - .env
    networks:
      - transcendence
  notification-service:
    container_name: notification-service
    build:
      context: ./apps
      dockerfile: notification-service/Dockerfile
    env_file:
      - .env
    networks:
      - transcendence
  frontend:
    container_name: frontend
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./apps/frontend/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./apps/frontend/src/index.html:/usr/share/nginx/html/index.html:ro
    networks:
      - transcendence
    depends_on:
      - auth-service
      # - user-service
      - notification-service

networks:
  transcendence:
    driver: bridge
