global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:

  # Prometheus itself
  - job_name: "prometheus"
    static_configs:
      - targets:
          - "prometheus:9090"

  # Auth service
  - job_name: "auth-service"
    metrics_path: /metrics
    static_configs:
      - targets:
          - "auth-service:3000"

  # User service
  - job_name: "user-service"
    metrics_path: /metrics
    static_configs:
      - targets:
          - "user-service:3001"

  # Notification service
  - job_name: "notification-service"
    metrics_path: /metrics
    static_configs:
      - targets:
          - "notification-service:3002"
