global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:

  # Prometheus itself
  - job_name: "prometheus"
    static_configs:
      - targets:
          - "prometheus:9090"

  # Auth service
  - job_name: "auth-service"
    metrics_path: /metrics
    static_configs:
      - targets:
          - "auth-service:3000"

  # User service
  - job_name: "user-service"
    metrics_path: /metrics
    static_configs:
      - targets:
          - "user-service:3001"

  # Notification service
  - job_name: "notification-service"
    metrics_path: /metrics
    static_configs:
      - targets:
          - "notification-service:3002"

  # Game service
  - job_name: "game-service"
    metrics_path: /metrics
    static_configs:
      - targets:
          - "game-service:3003"
        
  # Room service
  - job_name: "room-service"
    metrics_path: /metrics
    static_configs:
      - targets:
          - "room-service:3004"
      
  # Stats service
  - job_name: "stats-service"
    metrics_path: /metrics
    static_configs:
      - targets:
          - "stats-service:3005"

  # Chat service
  - job_name: "chat-service"
    metrics_path: /metrics
    static_configs:
      - targets:
          - "chat-service:3006"